//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjRentalManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class building
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public building()
        {
            this.apartments = new HashSet<apartment>();
        }
    
        public int buildingId { get; set; }

        [Required(ErrorMessage = "Address is required.")]
        [StringLength(50, ErrorMessage = "Address cannot exceed 50 characters.")]
        [Display(Name = "Address")]
        public string address { get; set; }

        [Required(ErrorMessage = "City is required.")]
        [StringLength(50, ErrorMessage = "City cannot exceed 50 characters.")]
        [Display(Name = "City")]
        public string city { get; set; }

        [Required(ErrorMessage = "Province is required.")]
        [StringLength(50, ErrorMessage = "Province cannot exceed 50 characters.")]
        [Display(Name = "Province / region")]
        public string province { get; set; }

        [Required(ErrorMessage = "Postal code is required.")]
        [StringLength(10, ErrorMessage = "Postal code cannot exceed 10 characters.")]
        [RegularExpression(@"^\d{5}$", ErrorMessage = "Use Pakistan format: 5 digits (e.g. 75500).")]
        [Display(Name = "Postal code")]
        public string postalCode { get; set; }

        [StringLength(500)]
        [Display(Name = "Building photo")]
        public string imagePath { get; set; }

        [Range(0, 5000, ErrorMessage = "Enter a value between 0 and 5000.")]
        [Display(Name = "Total units in this building")]
        public Nullable<int> totalUnits { get; set; }

        [Range(0, 5000, ErrorMessage = "Enter a value between 0 and 5000.")]
        [Display(Name = "Units currently available")]
        public Nullable<int> availableUnits { get; set; }

        [Required(ErrorMessage = "Owner ID is required.")]
        [Display(Name = "Owner ID")]
        public int ownerId { get; set; }

        [Required(ErrorMessage = "Manager ID is required.")]
        [Display(Name = "Manager ID")]
        public int managerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<apartment> apartments { get; set; }
        public virtual manager manager { get; set; }
        public virtual owner owner { get; set; }
    }
}
