//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated to match Model1.edmx (EntityContainer DbPropertyRentalEntities).
//     Regenerate from the EDMX designer when the model changes.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjRentalManagement.Models
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class DbPropertyRentalEntities : DbContext
    {
        public DbPropertyRentalEntities()
            : base("name=DbPropertyRentalEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<apartment> apartments { get; set; }
        public virtual DbSet<appointment> appointments { get; set; }
        public virtual DbSet<building> buildings { get; set; }
        public virtual DbSet<manager> managers { get; set; }
        public virtual DbSet<messageManager> messageManagers { get; set; }
        public virtual DbSet<messageOwner> messageOwners { get; set; }
        public virtual DbSet<owner> owners { get; set; }
        public virtual DbSet<tenant> tenants { get; set; }
        public virtual DbSet<eventOwner> eventOwners { get; set; }
        public virtual DbSet<booking> bookings { get; set; }
    }
}
