//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjRentalManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class owner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public owner()
        {
            this.buildings = new HashSet<building>();
            this.messageOwners = new HashSet<messageOwner>();
            this.eventOwners = new HashSet<eventOwner>();
        }

        [Display(Name = "Owner ID")]
        public int ownerId { get; set; }

        [Required(ErrorMessage = "Name is required.")]
        [Display(Name = "Owner Name")]
        public string name { get; set; }

        [Required(ErrorMessage = "Email is required.")]
        [EmailAddress(ErrorMessage = "Invalid Email Address.")]
        [Display(Name = "Email")]
        public string email { get; set; }

        [Required(ErrorMessage = "Password is required.")]
        [DataType(DataType.Password)]
        [StringLength(64, MinimumLength = 8, ErrorMessage = "The password must be between 8 and 64 characters.")]
        [Display(Name = "Password")]
        public string password { get; set; }

        [Required(ErrorMessage = "Phone number is required.")]
        [StringLength(15, MinimumLength = 11, ErrorMessage = "Enter a valid Pakistani mobile number (11 digits, e.g. 03XXXXXXXXX).")]
        [RegularExpression(@"^(?:\+92|0092)3\d{9}$|^03\d{9}$", ErrorMessage = "Use Pakistani mobile format: 03XXXXXXXXX or +923XXXXXXXXX.")]
        [Display(Name = "Mobile number (Pakistan)")]
        public string phoneNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<building> buildings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<messageOwner> messageOwners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eventOwner> eventOwners { get; set; }
    }
}
